#!/bin/bash

# Quick 'unblock ip addresses' script
# usage: ipt_unblock <file with ip addresses>

if [[ $EUID -ne 0 ]]; then
  echo "This script must be run with root privilegs"
  exit 1
fi

while read ip
do
  iptables -D INPUT -s $ip -j DROP
done < $1