#!/bin/bash

# Example config file, assumed to be found as 'config/example'
#
# server_host="db.example.com"
# server_user="example_user"
# server_password="password123"
# server_dbname="exampledb"
# dumpfile="/home/example_user/my_big_sql_dump.sql"
#
# This allows you to run 
# $> mysql_backup example

THISDIR=$(dirname $0)
if [ -f "${THISDIR}/config/${1}" ]; then
	echo "Found config file for: ${1}"
	source ${THISDIR}/config/${1}

	if [[ -z $server_host || -z $server_user || -z $server_password || -z $dumppath || -z $server_dbname ]]; then
	  echo 'Config file did not contain all desired variables.'
	  exit 1
	else
		echo "Dumping ${server_dbname} (this may take a while..)"
		mysqldump --single-transaction --quick --lock-tables=false --host=${server_host} --user=${server_user} --password=${server_password} --protocol=TCP ${server_dbname} > ${dumpfile}
	fi
else
	echo "Could not find config file for: ${1}"
fi